export const images = {
  auth: "/assets/auth.png",
  login: "/assets/login.png",
  icon: "/assets/Icon.png",
  Logo: "/assets/Logo.png",
  addnewicon: "/assets/addnewicon.png",
  complainticon: "/assets/complainticon.png",
  completedicon: "/assets/completedicon.png",
  managecomplainticon: "/assets/managecomplainticon.png",
  pending: "/assets/pending.png",
  processingicon: "/assets/processingicon.png",
  mangetemicon: "/assets/mangetemicon.png",
  workingicon: "/assets/workingicon.png",
  customerPng: "/assets/customerCarePNG.jpg",
  registeringComplaint: "/assets/complaintregisterpng.png",
  trackingComplaint: "/assets/TrackingComplaint.png",
  Spinner: "/assets/Spinner.svg",
  ComplaintRegisteration: "/assets/ComplaintRegisteration.png",
  ComplaintPage: "/assets/complaintpage.png",
  MainPicture: "/assets/MainPicture.png",
  ComplaintPicture: "/assets/ComplaintPicture.png",
  ComplaintTracking:"/assets/ComplaintTracking.png",
  NotFound:"/assets/NotFound.webp"
};
