import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="relative flex w-full flex-col min-h-screen">
            <main className="flex-1">{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
